// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egootnxenrdtsuyvabqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnb290bnhlbnJkdHN1eXZhYnFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzAwODYsImV4cCI6MjA2MDkwNjA4Nn0.nWcSGENvUX7MFuoECAHMUUezqfHALiUxtwDK4CxM--4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);